apiServer:
  port: 8080
  ssl:
    enabled: false
    keystore:
      path:
      password:
      type: JKS
      key-manager-password:

    truststore:
      path:
      password:
      trust-all: false

    protocols:
      ssl-protocol: TLS
      enabled:
        - TLSv1.2
        - TLSv1.3
      ciphers:
        - TLS_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

    client-auth:
      mode: NONE

    advanced:
      hostname-verification: true
      session-timeout: 86400
      ocsp-enabled: false
      crldp-enabled: false

    server:
      accept-count: 200
webhook:
  url: "https://your-webhook-endpoint.com"
  timeout: 5000
chat-messages:
  enabled: true
  send-interval: 20
  package-size: 10
achievements:
  enabled: true
server-info:
  enabled: true
  collection-interval: 60
  include-ping: true
  max-players-to-send: 50
